"""
Resume structure assessor and generator.

Two public functions:

* ``is_professional_structure(resume_text, sections)``
  Returns ``True`` if the resume already has an acceptable professional layout,
  ``False`` if it is missing key sections or is otherwise disorganised.

* ``ensure_professional_structure(resume_text, provider)``
  If the resume already looks professional, return it unchanged (``reformed=False``).
  Otherwise call the LLM provider to regenerate a properly structured version
  while preserving all original content (``reformed=True``).

Both functions are intentionally provider-agnostic: they accept the abstract
``LLMProvider`` interface so they work equally well with Groq, OpenAI, or
Anthropic.  BERT is used upstream for semantic scoring and is unaffected.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass

logger = logging.getLogger(__name__)

# Minimum required sections for a "professional" resume
_REQUIRED_SECTIONS = {"experience", "education", "skills"}

# Minimum fraction of required sections that must be detected
_MIN_SECTION_COVERAGE = 0.67  # at least 2 of 3 required sections


@dataclass
class StructureAssessment:
    """Result of assessing a resume's structure quality."""
    is_professional: bool
    detected_sections: list[str]
    missing_sections: list[str]
    reason: str


def _load_structure_prompt() -> str:
    prompt_path = os.path.join(
        os.path.dirname(__file__), '..', 'prompts', 'structure_prompt.txt'
    )
    if os.path.exists(prompt_path):
        with open(prompt_path, 'r', encoding='utf-8') as f:
            return f.read()
    # Minimal fallback
    return (
        "You are an expert resume formatter. "
        "Reorganise the resume into standard professional sections "
        "(Contact, Summary, Skills, Work Experience, Education) "
        "preserving ALL original content. Return ONLY the restructured resume text."
    )


def assess_structure(
    resume_text: str,
    sections: dict[str, str],
) -> StructureAssessment:
    """
    Evaluate whether a resume already has an acceptable professional structure.

    Parameters
    ----------
    resume_text:  Full plain text of the resume.
    sections:     Output of ``detect_sections()`` — mapping section_name → content.

    Returns
    -------
    StructureAssessment  with ``is_professional`` set accordingly.
    """
    # Which required sections were actually detected with non-empty content?
    detected = [s for s in _REQUIRED_SECTIONS if sections.get(s, "").strip()]
    missing  = [s for s in _REQUIRED_SECTIONS if s not in detected]

    coverage = len(detected) / len(_REQUIRED_SECTIONS)

    # Additional heuristic: very short resumes probably lack structure
    too_short = len(resume_text.strip()) < 200

    if too_short:
        return StructureAssessment(
            is_professional=False,
            detected_sections=detected,
            missing_sections=missing,
            reason="Resume text is too short to contain a professional structure.",
        )

    if coverage < _MIN_SECTION_COVERAGE:
        return StructureAssessment(
            is_professional=False,
            detected_sections=detected,
            missing_sections=missing,
            reason=(
                f"Only {len(detected)}/{len(_REQUIRED_SECTIONS)} required sections detected "
                f"({', '.join(missing)} missing or unrecognised)."
            ),
        )

    return StructureAssessment(
        is_professional=True,
        detected_sections=list(sections.keys()),
        missing_sections=missing,
        reason="Sufficient professional sections detected.",
    )


def ensure_professional_structure(
    resume_text: str,
    provider,
    sections: dict[str, str],
) -> tuple[str, bool]:
    """
    Guarantee that the returned resume text has a professional layout.

    If the uploaded resume already looks professional, it is returned
    unchanged (``reformed = False``).

    If the structure is messy or key sections are absent, the LLM provider
    is called once to reorganise the content into standard professional
    sections — all original facts are preserved, nothing is invented.

    Parameters
    ----------
    resume_text:  Full plain text extracted from the uploaded resume.
    provider:     Any ``LLMProvider`` instance (Groq / OpenAI / Anthropic).
    sections:     Pre-computed ``detect_sections()`` output.

    Returns
    -------
    (structured_text, reformed)
        structured_text — the (possibly regenerated) resume text.
        reformed        — ``True`` if the structure was regenerated by the LLM.
    """
    assessment = assess_structure(resume_text, sections)

    if assessment.is_professional:
        logger.info(
            f"[Structurer] Resume structure is already professional "
            f"({assessment.reason})"
        )
        return resume_text, False

    logger.info(
        f"[Structurer] Messy/incomplete structure detected: {assessment.reason}. "
        f"Calling {provider.name} to regenerate structure…"
    )

    system_prompt = _load_structure_prompt()
    user_message  = (
        "Please restructure the following resume into a clean, professional layout "
        "following the rules in your instructions.  "
        "Preserve every piece of information — do not add or remove anything.\n\n"
        f"ORIGINAL RESUME:\n{resume_text[:6000]}"
    )

    try:
        structured_text = provider.complete(
            system_prompt=system_prompt,
            user_message=user_message,
            max_tokens=3000,
            temperature=0.2,   # Low temperature for factual restructuring
        )
        structured_text = structured_text.strip()

        if len(structured_text) < 100:
            logger.warning(
                "[Structurer] LLM returned suspiciously short structured text; "
                "falling back to original."
            )
            return resume_text, False

        logger.info(
            f"[Structurer] Structure reformed successfully "
            f"({len(resume_text)} → {len(structured_text)} chars)"
        )
        return structured_text, True

    except Exception as exc:
        logger.error(
            f"[Structurer] LLM structuring call failed ({exc}); "
            "falling back to original resume text."
        )
        return resume_text, False
